### ISSUE TITLE
Getting a Subsequenz of the Data

### ISSUE THREAD

**Issue by DL9HDA** [philrawlings/bluepill-usb-cdc-test#1]
Hello, this is the first implementation that works very very well! I have an application where via USB data can come with different length. I would like to pass these simply over another UART. Between 8 and 800 bytes everything is possible.I have set the buffer from 256 to 1024. Partly the data comes without a break.  From all this data I want to find substrings. Let's say there would be permanently transmitted messages and I would like to find the position where e.g. "British Airways" appears and let's say pick up the 20 bytes after that. Is such a thing possible? The messages are never the same length and the position where a search word appears is highly variable. Cheers, Holger

**Comment by philrawlings** [comment]
Probably the easiest way is to read one byte at a time in the main loop maintaining a buffer of the last 40 bytes. When your buffer contains "British Airways" plus 20 additional bytes, you can then perform the action you need.

Note that this is not the same buffer as the one in `usbd_cdc_if.c` - increasing that one to be larger than the maximum total size of a message is a good idea to be safe, but so long as you are reading data out in your main loop as soon as possible it shouldnt hit the max size anyway (as USB data packets arrive in up to 64 byte chunks).

**Comment by DL9HDA** [comment]
Hello, thank you very much for your answer. I am still quite new to 
STM32 and C. I have spent many years with 8-bit Atmel and assembler. So 
maybe the question is a bit awkward.

In the main routine, the rx buffer is limited to 8 bytes uint8_t 
rxData[8];

In the debugger I saw that these 8 bytes are overwritten again and 
again. So when I send abcdefgh1, there is 1bcdefgh in the buffer.

Couldn't it be increased? E.g. to 64 or even more?

Many greetings
Holger




Am 2021-05-15 12:52, schrieb Phil Rawlings:

**Comment by philrawlings** [comment]
The `rxData` buffer is just how many bytes you want to read at a time - it can be however big or small you want it to be, I only chose 8 as an example. However if you make it bigger it wont return anything until at least that number of bytes have been received. So in your case you really want to receive *one* byte at a time, then collect those bytes in your application until a run of them contain the pattern you want.
I'm planning on adding a`ReadByte` function at some point for just reading a single byte, however you can do that now by just setting `bytesToRead` to 1 and reducing the rxData array size to 1. Obviously that byte will get overwritten each time the read buffer function is called, so your application needs to maintain its own circular buffer for character sequence matching.

**Comment by philrawlings** [comment]
Closing issue as this is a discussion of how to use the functions rather than something that needs fixing
