### ISSUE TITLE
BUGG in CDC_PeekRxBuffer_FS()

### ISSUE THREAD

**Issue by edrotleff** [philrawlings/bluepill-usb-cdc-test#2]
The function reads in the loop from constant element into target buffer "Buf":

for (uint8_t i = 0; i < Len; i++) {
    Buf[i] = rxBuffer[rxBufferTailPos]; // Get data without incrementing the tail position
  }

it should be like this:

for (uint8_t i = 0; i < Len; i++) {
    Buf[i] = rxBuffer[ (rxBufferTailPos + i) % HL_RX_BUFFER_SIZE]; // Get data without incrementing the tail position
  }
best regards - Elias

**Comment by philrawlings** [comment]
Pull request from @macaba fixed this issue
